In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import mplfinance as mpf
import datetime as dt

In [11]:
tickers=["AAPL","AMZN","MSFT","NVDA","TSLA","BAC","SPY","INTC","JPM","GOOGL","QQQ","IWM","SOFI","XLF","CSCO","NFLX",\
        "AMD","SHOP","XOM","INTU","OXY"]

In [12]:
ohlc_intra={} #directory with ohlc value for each stock
#start=dt.datetime.today()-dt.timedelta(days=1)
start=dt.datetime.today()
end=dt.datetime.today()

for ticker in tickers:
    ohlc_intra[ticker]=yf.download(ticker,period='1d',interval='5m')
    ohlc_intra[ticker].dropna(inplace=True,how="all")

tickers=ohlc_intra.keys()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
tickers

dict_keys(['AAPL', 'AMZN', 'MSFT', 'NVDA', 'TSLA', 'BAC', 'SPY', 'INTC', 'JPM', 'GOOGL', 'QQQ', 'IWM', 'SOFI', 'XLF', 'CSCO', 'NFLX', 'AMD', 'SHOP', 'XOM', 'INTU', 'OXY'])

In [14]:
# for ticker in tickers:
#     trend=[]
#     for i in range(len(ohlc_intra[ticker])):
#         #print(spy['Open'][i],spy['Close'][i])
#         if (ohlc_intra[ticker]['Open'][i]>ohlc_intra[ticker]['Open'][i-1] and ohlc_intra[ticker]['Close'][i]>ohlc_intra[ticker]['Close'][i-1]) and \
#         (ohlc_intra[ticker]['Open'][i-1]>ohlc_intra[ticker]['Open'][i-2] and ohlc_intra[ticker]['Close'][i-1]>ohlc_intra[ticker]['Close'][i-2]):
#             trend.append('Up')
#         elif (ohlc_intra[ticker]['Open'][i]<ohlc_intra[ticker]['Open'][i-1] and ohlc_intra[ticker]['Close'][i]<ohlc_intra[ticker]['Close'][i-1]) and \
#         (ohlc_intra[ticker]['Open'][i-1]<ohlc_intra[ticker]['Open'][i-2] and ohlc_intra[ticker]['Close'][i-1]<ohlc_intra[ticker]['Close'][i-2]):
#             trend.append('Down')
#         else:
#             trend.append('No signal')
#     ohlc_intra[ticker]['Trend']=trend

In [15]:
for ticker in tickers:
    trend=[]
    for i in range(len(ohlc_intra[ticker])):
        
        #condition of uptrend
        if (ohlc_intra[ticker]['Open'][i]>ohlc_intra[ticker]['Open'][i-1] and ohlc_intra[ticker]['Close'][i]>ohlc_intra[ticker]['Close'][i-1]) and \
        (ohlc_intra[ticker]['Open'][i-1]>ohlc_intra[ticker]['Open'][i-2] and ohlc_intra[ticker]['Close'][i-1]>ohlc_intra[ticker]['Close'][i-2]):
            trend.append(1)
        #condition of downtrend
        elif (ohlc_intra[ticker]['Open'][i]<ohlc_intra[ticker]['Open'][i-1] and ohlc_intra[ticker]['Close'][i]<ohlc_intra[ticker]['Close'][i-1]) and \
        (ohlc_intra[ticker]['Open'][i-1]<ohlc_intra[ticker]['Open'][i-2] and ohlc_intra[ticker]['Close'][i-1]<ohlc_intra[ticker]['Close'][i-2]):
            trend.append(-1)
            
        else:
            trend.append(0)
    ohlc_intra[ticker]['Trend']=trend
    ohlc_intra[ticker]['Cum_Trend']=ohlc_intra[ticker]['Trend'].cumsum()

In [16]:
# dictionary method
trending={}
for ticker in tickers:
    trending[ticker]=ohlc_intra[ticker]['Cum_Trend']

In [17]:
#Dataframe method
df=pd.DataFrame()
for ticker in tickers:
    df[ticker]=ohlc_intra[ticker]['Cum_Trend']

In [18]:
df

,AAPL,AMZN,MSFT,NVDA,TSLA,BAC,SPY,INTC,JPM,GOOGL,...,IWM,SOFI,XLF,CSCO,NFLX,AMD,SHOP,XOM,INTU,OXY
Datetime,,,,,,,,,,,,,,,,,,,,,
2022-11-02 09:30:00-04:00,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
2022-11-02 09:35:00-04:00,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
2022-11-02 09:40:00-04:00,1,0,-1,0,0,0,-1,0,0,0,...,0,1,0,0,-1,0,0,1,0,1
2022-11-02 09:45:00-04:00,1,0,-1,1,1,-1,-2,1,-1,0,...,0,1,0,-1,-2,1,1,1,1,1
2022-11-02 09:50:00-04:00,1,0,-1,1,2,-1,-2,2,-1,0,...,0,1,0,-2,-2,1,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-02 15:40:00-04:00,-1,-10,-7,-4,-10,3,-1,-3,-1,-8,...,-4,-11,-2,-4,-11,-4,-6,2,-3,0
2022-11-02 15:45:00-04:00,-1,-10,-7,-4,-10,3,-1,-3,-1,-8,...,-4,-11,-2,-4,-11,-4,-6,2,-3,0
2022-11-02 15:50:00-04:00,-2,-10,-7,-4,-10,2,-2,-4,-2,-9,...,-5,-11,-3,-5,-12,-4,-7,2,-4,-1
2022-11-02 15:55:00-04:00,-3,-11,-8,-5,-11,2,-3,-5,-2,-10,...,-6,-11,-4,-6,-13,-5,-8,2,-5,-1
2022-11-02 16:00:00-04:00,-3,-11,-8,-5,-11,2,-3,-5,-2,-10,...,-6,-11,-4,-6,-13,-6,-9,2,-5,-1

In [10]:
df.to_csv("all.csv")

In [10]:
ohlc_intra['MSFT'].to_csv('msft.csv')

In [11]:
#ohlc_intra['AMZN'].to_csv("amzn.csv")

In [12]:
#ohlc_intra['TSLA'].to_csv("tsla.csv")

In [13]:
#ohlc_intra['AAPL'].to_csv('aapl.csv')